### ISSUE TITLE
Qual o nome da aplicação?

### ISSUE THREAD

**Issue by Luiz-Ossinho** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t1-adocao-caridosa-de-animais#11]
Já esta ficando difícil usar o nome "Adoção caridosa/solidaria de animais (Nome temporário)"  em vários lugares.
Vou marcar esse issue nos lugares que estiverem usando para manter a documentação atualizada posteriormente.

**Comment by Rafael-Pedro** [comment]
DogCat - Adote seu pet.

**Comment by Adeilton-Ro** [comment]
Acredito que possa ser "AdoPets" mas já existe uma organização com esse nome.

**Comment by Vasconcelos-Carlos** [comment]
Equipe Cão

**Comment by Adeilton-Ro** [comment]
AnimalGroup

**Comment by GusTav0HenriQue** [comment]
PetAoResgate

**Comment by Luiz-Ossinho** [comment]
Equipe Cão é vencedora.
