### ISSUE TITLE
Qual a modelagem de ONG vs Usuario/Tutor

### ISSUE THREAD

**Issue by Luiz-Ossinho** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t1-adocao-caridosa-de-animais#4]
Nesse sistema precisa existe organizações, que podem ter mais de um membro e usuários que não são membros de organizações mas podem solicitar o registro em uma organização, ou solicitar a adoção de algum animal.
Durante o registro, como essas informacoes serao solicitadas? é possivel criar um usuario e uma ONG ao mesmo tempo?

**Comment by Adeilton-Ro** [comment]
Cada ONG será uma conta, da mesma forma que os usuários. A única diferença entre eles vão ser as funcionalidades que eles tem acesso. Mas se for do desejo de todos os colaboradores, um ONG pode sim ser um conjunto de contas de usuários que participam daquela instituição, podemos abrir como tópico para ser discutido em reunião.

**Comment by Luiz-Ossinho** [comment]
Em refinamento, decidimos na seguinte modelagem: 
Cada ONG será uma conta, da mesma forma que os usuários.
